# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 077663be75b8d46ff77ef8f54dad79629ea4d967d9cec2a7d60681b6475fac43006d1fb7f5bf23815a76b5fcc1432b5ccb7561758184630dfccde5902ac1eaf8

test:
  secret_key_base: aa74a62594f779cf17c86626ecf12bb639e818df608f46d4a55efb218ae8f92d0671e75191942b0b68ffbab036b2d6b0d7f864da7c563b82f45956f629b0a8d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
